### ISSUE TITLE
Turn CreateFlags into a builder pattern

### ISSUE THREAD

**Issue by Lisoph** [Lisoph/nanovg-rs#3]
Generally a builder pattern is preferred to bitflags in Rust. Therefore, rewriting the `CreateFlags` struct to a `Context` builder is probably cleaner.

The reason I'm unsure is because there aren't many flags at all, 3 in total. Is this really worth forcing a builder pattern onto the programmer?

**Comment by mthiesen** [comment]
Would it make sense to move the GL version selection to `CreateFlags` as well? Right now I find it a little bit weird that you have to call different functions depending on the GL version you want to use.

**Comment by Lisoph** [comment]
Yes, good idea! If think this is a another very good case for turning the flags into a builder pattern.

**Comment by Lisoph** [comment]
Implemented in ccc74287a27d4e09660b8ea47840a7482ff4a5a4.
