### ISSUE TITLE
Get rid of the nanovg warnings

### ISSUE THREAD

**Issue by Lisoph** [Lisoph/nanovg-rs#4]
A lot of nanovg warnings appear when one builds the library. We don't want that!

I think the only solution here is to fix the warnings within nanovg itself, not much we can do in the bindings.

**Comment by mthiesen** [comment]
Another solution would be to use `gcc::Build::flag` to silence the specific warnings. This way there is no need to modify nanovg.

**Comment by Lisoph** [comment]
Great idea! I've used your suggestion to hide the warnings.

Fixed with f9044273663778d3a7cf2aae78cace1254b603dc.
