### ISSUE TITLE
Make open SubPaths possible

### ISSUE THREAD

**Issue by mthiesen** [Lisoph/nanovg-rs#5]
Currently it is not possible to draw an open `SubPath`. The `sub_path` function always calls `nvgClosePath`. I would suggest to introduce a new `SubPath` function called `close`. This would also mirror the behavior of _NanoVG_ where all paths are open unless closed explicitly by calling `nvgClosePath`.

**Comment by Lisoph** [comment]
I guess with the merge of your pull request, this is now closed ;).
